apiVersion: v1
kind: Pod
metadata:
    annotations:
        fixora.io/repo-path: pod.yaml
        fixora.io/repo-url: https://github.com/baka126/fixora-demo.git
        fixora.io/vcs-type: github
    name: oom-test-4
spec:
    containers:
        - args:
            - --vm
            - "1"
            - --vm-bytes
            - 500M
            - --vm-hang
            - "1"
          image: alexeiled/stress-ng
          name: stress
          resources:
            limits:
                memory: 100Mi
    restartPolicy: Never
